Make sure that a Content-type is set and HEAD requests don't receive a body.
This happens because part of Sinatra's processing is skipped when a throw call is received. I've now duplicated that functionality in the test functions so it matches production behavior.

Previously all tests would fail like so:

NoMethodError: undefined method `empty?' for nil:NilClass
    /Users/mcolyer/.rvm/gems/ree-1.8.7-2010.02@async_sinatra/gems/rack-1.2.2/lib/rack/mock.rb:152:in `initialize'
    /Users/mcolyer/.rvm/gems/ree-1.8.7-2010.02@async_sinatra/gems/rack-1.2.2/lib/rack/utils.rb:305:in `each'
    /Users/mcolyer/.rvm/gems/ree-1.8.7-2010.02@async_sinatra/gems/rack-1.2.2/lib/rack/utils.rb:304:in `each'
    /Users/mcolyer/.rvm/gems/ree-1.8.7-2010.02@async_sinatra/gems/rack-1.2.2/lib/rack/mock.rb:150:in `initialize'
    /Users/mcolyer/Code/async_sinatra/lib/sinatra/async/test.rb:53:in `new'
    /Users/mcolyer/Code/async_sinatra/lib/sinatra/async/test.rb:53:in `handle_last_response'
    /Users/mcolyer/Code/async_sinatra/lib/sinatra/async/test.rb:34:in `request'
    /Users/mcolyer/Code/async_sinatra/lib/sinatra/async.rb:82:in `[]'
    /Users/mcolyer/Code/async_sinatra/lib/sinatra/async.rb:82:in `body'
    ./test/test_async.rb:86:in `AGET /agents -1873668453'